#! /bin/bash


#  $██████╗$██████╗$███╗$$$██╗███████╗██╗$██████╗$
#  ██╔════╝██╔═══██╗████╗$$██║██╔════╝██║██╔════╝$
#  ██║$$$$$██║$$$██║██╔██╗$██║█████╗$$██║██║$$███╗
#  ██║$$$$$██║$$$██║██║╚██╗██║██╔══╝$$██║██║$$$██║
#  ╚██████╗╚██████╔╝██║$╚████║██║$$$$$██║╚██████╔╝
#  $╚═════╝$╚═════╝$╚═╝$$╚═══╝╚═╝$$$$$╚═╝$╚═════╝$
#  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


if [ $(xrandr --query | grep -w 'connected' | wc -l) -gt 1 ]; then
	xrandr --output DisplayPort-0 --set TearFree on
	xrandr --output DisplayPort-1 --set TearFree off
	xrandr --output DisplayPort-0 --mode 1920x1080 --pos 0x0 --right-of DisplayPort-1 --rate 144 --primary
	xrandr --output DisplayPort-1 --scale 1.2x1.2 --pos -568x0 --rotate left
	bspc monitor DisplayPort-0 -d 1 2 3 4 5
	bspc monitor DisplayPort-1 -d 6 7 8 9 10
	bspc wm -O DisplayPort-0 DisplayPort-1
else
	xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144 --rotate normal --primary
	bspc monitor DisplayPort-0 -d 1 2 3 4 5
fi

bspc config top_padding                 30
bspc config left_padding                0
bspc config right_padding               0
bspc config bottom_padding              0
bspc config window_gap                  10
bspc config border_width                0
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action2             resize_corner


#  ██████╗$██╗$$$██╗██╗$$$$$███████╗███████╗
#  ██╔══██╗██║$$$██║██║$$$$$██╔════╝██╔════╝
#  ██████╔╝██║$$$██║██║$$$$$█████╗$$███████╗
#  ██╔══██╗██║$$$██║██║$$$$$██╔══╝$$╚════██║
#  ██║$$██║╚██████╔╝███████╗███████╗███████║
#  ╚═╝$$╚═╝$╚═════╝$╚══════╝╚══════╝╚══════╝
#  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


bspc rule -a Pavucontrol state=floating center=true
bspc rule -a lite-xl state=fullscreen
bspc rule -a ymwp.YandexMusicWavePlayer state=floating sticky=on


#  $█████╗$██╗$$$██╗████████╗$██████╗$███████╗████████╗$█████╗$██████╗$████████╗
#  ██╔══██╗██║$$$██║╚══██╔══╝██╔═══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝
#  ███████║██║$$$██║$$$██║$$$██║$$$██║███████╗$$$██║$$$███████║██████╔╝$$$██║$$$
#  ██╔══██║██║$$$██║$$$██║$$$██║$$$██║╚════██║$$$██║$$$██╔══██║██╔══██╗$$$██║$$$
#  ██║$$██║╚██████╔╝$$$██║$$$╚██████╔╝███████║$$$██║$$$██║$$██║██║$$██║$$$██║$$$
#  ╚═╝$$╚═╝$╚═════╝$$$$╚═╝$$$$╚═════╝$╚══════╝$$$╚═╝$$$╚═╝$$╚═╝╚═╝$$╚═╝$$$╚═╝$$$
#  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

for pid in `ps -ef | grep dbus-daemon | awk '{print $2}'` ; do kill $pid ; done
pkill dbus-launch
pkill dunst
pkill clipit

pgrep -x sxhkd > /dev/null || sxhkd &
bspwm -c $HOME/.config/bspwm/bspwmrc &
dbus-launch dunst &
setxkbmap -option grp:alt_shift_toggle us,ru &
xset r rate 250 50 &
feh --bg-scale $HOME/.config/wallpapers/wallpapers.png &
compfy --config=$HOME/.config/compfy/compfy.conf &
xscreensaver --no-splash &
xsetroot -cursor_name left_ptr &
clipit &
$HOME/.config/polybar/launch.sh &
