#! /bin/sh


#  $██████╗$██████╗$███╗$$$██╗███████╗██╗$██████╗$
#  ██╔════╝██╔═══██╗████╗$$██║██╔════╝██║██╔════╝$
#  ██║$$$$$██║$$$██║██╔██╗$██║█████╗$$██║██║$$███╗
#  ██║$$$$$██║$$$██║██║╚██╗██║██╔══╝$$██║██║$$$██║
#  ╚██████╗╚██████╔╝██║$╚████║██║$$$$$██║╚██████╔╝
#  $╚═════╝$╚═════╝$╚═╝$$╚═══╝╚═╝$$$$$╚═╝$╚═════╝$
#  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


bspc monitor -d I II III IV V

bspc config border_width		0
bspc config window_gap			10
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_side
bspc config pointer_action2 		resize_corner


#  ██████╗$██╗$$$██╗██╗$$$$$███████╗███████╗
#  ██╔══██╗██║$$$██║██║$$$$$██╔════╝██╔════╝
#  ██████╔╝██║$$$██║██║$$$$$█████╗$$███████╗
#  ██╔══██╗██║$$$██║██║$$$$$██╔══╝$$╚════██║
#  ██║$$██║╚██████╔╝███████╗███████╗███████║
#  ╚═╝$$╚═╝$╚═════╝$╚══════╝╚══════╝╚══════╝
#  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


bspc rule -a Pavucontrol state=floating center=true


#  $█████╗$██╗$$$██╗████████╗$██████╗$███████╗████████╗$█████╗$██████╗$████████╗
#  ██╔══██╗██║$$$██║╚══██╔══╝██╔═══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝
#  ███████║██║$$$██║$$$██║$$$██║$$$██║███████╗$$$██║$$$███████║██████╔╝$$$██║$$$
#  ██╔══██║██║$$$██║$$$██║$$$██║$$$██║╚════██║$$$██║$$$██╔══██║██╔══██╗$$$██║$$$
#  ██║$$██║╚██████╔╝$$$██║$$$╚██████╔╝███████║$$$██║$$$██║$$██║██║$$██║$$$██║$$$
#  ╚═╝$$╚═╝$╚═════╝$$$$╚═╝$$$$╚═════╝$╚══════╝$$$╚═╝$$$╚═╝$$╚═╝╚═╝$$╚═╝$$$╚═╝$$$
#  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


pgrep -x sxhkd > /dev/null || sxhkd &

bspwm -c $HOME/.config/bspwm/bspwmrc &

xsetroot -cursor_name left_ptr &

dbus-launch dunst &

#xrandr --output DisplayPort-0 --mode 1920x1080 --rate 165

setxkbmap -option grp:alt_shift_toggle us,ru &

xset r rate 250 50

numlockx &

feh --bg-scale $HOME/.config/wallpapers/wallpapers.png &

compfy --config=$HOME/.config/compfy/compfy.conf &

xscreensaver --no-splash &

sleep 0.5

$HOME/.config/polybar/launch.sh &
