#! /bin/sh

bspc monitor -d I II III IV V

#CONFIG

bspc config border_width		0
bspc config window_gap			10
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true

#RULES

bspc rule -a Pavucontrol state=floating center=true

#AUTOSTART

bspwm -c $HOME/.config/bspwm/bspwmrc &

xsetroot -cursor_name left_ptr &

dbus-launch dunst &

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -option grp:alt_shift_toggle ru,us &

numlockx &

feh --bg-scale .config/wallpapers/blue3.png &

$HOME/.config/polybar/launch.sh &

sleep 0.05

compfy --config=$HOME/.config/compfy/compfy.conf &

xscreensaver --no-splash &
