

#  $██████╗$██████╗$██╗$$$$$$██████╗$██████╗$███████╗
#  ██╔════╝██╔═══██╗██║$$$$$██╔═══██╗██╔══██╗██╔════╝
#  ██║$$$$$██║$$$██║██║$$$$$██║$$$██║██████╔╝███████╗
#  ██║$$$$$██║$$$██║██║$$$$$██║$$$██║██╔══██╗╚════██║
#  ╚██████╗╚██████╔╝███████╗╚██████╔╝██║$$██║███████║
#  $╚═════╝$╚═════╝$╚══════╝$╚═════╝$╚═╝$$╚═╝╚══════╝
#  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#1e1e23"
foreground = "#d3c6aa"


#  $██████╗$██████╗$███╗$$$██╗███████╗██╗$██████╗$
#  ██╔════╝██╔═══██╗████╗$$██║██╔════╝██║██╔════╝$
#  ██║$$$$$██║$$$██║██╔██╗$██║█████╗$$██║██║$$███╗
#  ██║$$$$$██║$$$██║██║╚██╗██║██╔══╝$$██║██║$$$██║
#  ╚██████╗╚██████╔╝██║$╚████║██║$$$$$██║╚██████╔╝
#  $╚═════╝$╚═════╝$╚═╝$$╚═══╝╚═╝$$$$$╚═╝$╚═════╝$
#  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrains Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrains Mono"
style = "Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Light"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[window]
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 14
y = 12
